# Generated by Django 4.1.4 on 2024-01-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='Логин', max_length=500, verbose_name='Логин')),
                ('avatar', models.ImageField(default='img/personal-img.png', upload_to='avatars/', verbose_name='Аватарка')),
                ('name', models.CharField(default='Фамилия Имя Отчество', max_length=500, verbose_name='ФИО')),
                ('group', models.CharField(default='Ваша группа', max_length=500, verbose_name='Группа')),
                ('is_superuser', models.CharField(default=False, max_length=500, verbose_name='Суперпользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('category', models.CharField(max_length=500, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'категорию знака',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='ExamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='Логин', max_length=500, verbose_name='Логин')),
                ('res', models.CharField(default='-', max_length=500, verbose_name='Результат')),
                ('startTime', models.CharField(default='-', max_length=500, verbose_name='Время начала экзамена')),
                ('time', models.CharField(default='-', max_length=500, verbose_name='Время прохождения экзамена')),
            ],
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название знака')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание знака')),
                ('category', models.CharField(choices=[('all-signs', 'all-signs'), ('geodetic-points', 'geodetic-points'), ('localities', 'localities'), ('objects', 'objects'), ('road-network', 'road-network'), ('car-road', 'car-road'), ('structures', 'structures'), ('relief', 'relief'), ('vegetation-cover', 'vegetation-cover'), ('borders', 'borders'), ('color-scale', 'color-scale'), ('abbreviations', 'abbreviations')], max_length=500, verbose_name='Категория')),
                ('complexity', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], max_length=500, verbose_name='Сложность')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Изображение знака')),
                ('realObjectPhoto', models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение реального объекта')),
                ('question1', models.CharField(blank=True, max_length=500, verbose_name='Вопрос 1')),
                ('answer1', models.CharField(blank=True, max_length=500, verbose_name='Ответ 1')),
                ('question2', models.CharField(blank=True, max_length=500, verbose_name='Вопрос 2')),
                ('answer2', models.CharField(blank=True, max_length=500, verbose_name='Ответ 2')),
                ('question3', models.CharField(blank=True, max_length=500, verbose_name='Вопрос 3')),
                ('answer3', models.CharField(blank=True, max_length=500, verbose_name='Ответ 3')),
                ('question4', models.CharField(blank=True, max_length=500, verbose_name='Вопрос 4')),
                ('answer4', models.CharField(blank=True, max_length=500, verbose_name='Ответ 4')),
                ('question5', models.CharField(blank=True, max_length=500, verbose_name='Вопрос 5')),
                ('answer5', models.CharField(blank=True, max_length=500, verbose_name='Ответ 5')),
            ],
            options={
                'verbose_name': 'знак',
                'verbose_name_plural': 'Добавить знак',
            },
        ),
    ]
