# Generated by Django 4.1.7 on 2023-04-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='sign',
            name='category',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sign',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sign',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
