# Generated by Django 4.1.4 on 2023-05-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Описание знака'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='realObjectPhoto',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение реального объекта'),
        ),
    ]
