# Generated by Django 4.1.4 on 2023-05-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_sign_description_alter_sign_realobjectphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='description',
        ),
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
    ]
