# Generated by Django 4.1.4 on 2023-05-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_test_description_remove_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Описание знака'),
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название знака'),
        ),
    ]
