# Generated by Django 4.1.4 on 2023-05-25 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_test_description_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='realObjectPhoto',
        ),
    ]
