# Generated by Django 4.1.4 on 2023-05-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_test_realobjectphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='realObjectPhoto',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение реального объекта'),
        ),
    ]
