# Generated by Django 4.1.4 on 2023-07-03 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_test_realobjectphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='description',
        ),
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
    ]
