# Generated by Django 4.1.4 on 2023-07-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_test_description_remove_test_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('category', models.CharField(max_length=500, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'категорию знака',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.AlterField(
            model_name='sign',
            name='category',
            field=models.CharField(choices=[(1, 1)], max_length=1, verbose_name='Категория'),
        ),
    ]
