# Generated by Django 4.1.4 on 2023-10-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_category_alter_sign_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='Логин', max_length=500, verbose_name='Логин')),
                ('avatar', models.ImageField(default='/static/img/personal-img.png', upload_to='img/', verbose_name='Аватарка')),
                ('name', models.CharField(default='Фамилия Имя Отчество', max_length=500, verbose_name='ФИО')),
                ('group', models.CharField(default='Ваша группа', max_length=500, verbose_name='Группа')),
            ],
        ),
        migrations.AlterField(
            model_name='sign',
            name='category',
            field=models.CharField(choices=[(1, 1)], max_length=500, verbose_name='Категория'),
        ),
    ]
