# Generated by Django 4.2.2 on 2023-11-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_exam_alter_additionalinfouser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='answer',
            field=models.CharField(blank=True, max_length=5000, verbose_name='Ответы (вводить через запятую)'),
        ),
        migrations.AlterField(
            model_name='additionalinfouser',
            name='avatar',
            field=models.ImageField(default='img/personal-img.png', upload_to='avatars/', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question',
            field=models.CharField(max_length=5000, verbose_name='Вопросы (вводить через запятую)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer',
            field=models.CharField(max_length=5000, verbose_name='Ответы (вводить через запятую)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='question',
            field=models.CharField(max_length=5000, verbose_name='Вопросы (вводить через запятую)'),
        ),
    ]
