# Generated by Django 4.2.2 on 2023-11-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_exam_answer_alter_additionalinfouser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='answer',
            field=models.CharField(max_length=5000, verbose_name='Ответы (вводить через запятую)'),
        ),
    ]
